#! /usr/bin/env lua
require "luarocks.require"
require "haml"

local i = 0
for line in io.lines(arg[1]) do
  local t = haml.lexer.tokenize_line(line)
  local buffer = {}
  i = i + 1
  for k, v in pairs(t) do
    table.insert(buffer, k .. ': "' .. v .. '"')
  end
  print(i .. '. ' .. table.concat(buffer, ", ")) end